server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///C:/Projects/PFEFinatech/config-server/configrepo
          default-label: main
          clone-on-start: false